package music;

public class MusicList {

    public static Music[] allMusic() {
        return new Music[] {
                new Music("deadmau5", "EDM", "Random Album Title", "Sometimes Things Get, Whatever"),
                new Music("deadmau5", "EDM", "Random Album Title", "Complications"),
                new Music("deadmau5", "EDM", "Random Album Title", "Slip"),
                new Music("deadmau5", "EDM", "Random Album Title", "Some Kind Of Blue"),
                new Music("deadmau5", "EDM", "Random Album Title", "Brazil (2nd Edit)"),
                new Music("deadmau5", "EDM", "Random Album Title", "Alone With You"),
                new Music("deadmau5", "EDM", "Random Album Title", "I Remember (with Kaskade; vocals by Haley Gibby; co-written by Ryan Raddon and Finn Bjarnson)"),
                new Music("deadmau5", "EDM", "Random Album Title", "Faxing Berlin (Piano Acoustic Version)"),
                new Music("deadmau5", "EDM", "Random Album Title", "Faxing Berlin"),
                new Music("deadmau5", "EDM", "Random Album Title", "Not Exactly"),
                new Music("deadmau5", "EDM", "Random Album Title", "Arguru (co-written by Chris Lake)"),
                new Music("deadmau5", "EDM", "Random Album Title", "So There I Was"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "FML"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Moar Ghosts 'n' Stuff"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Ghosts 'n' Stuff (featuring Rob Swire)"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Hi Friend! (featuring MC Flipside)"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Bot"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Word Problems"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Soma"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Lack of a Better Name"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "The 16th Hour"),
                new Music("deadmau5", "EDM", "For Lack of a Better Name", "Strobe"),
                new Music("deadmau5", "EDM", "4x4=12", "Some Chords"),
                new Music("deadmau5", "EDM", "4x4=12", "Sofi Needs a Ladder (featuring SOFI)"),
                new Music("deadmau5", "EDM", "4x4=12", "City In Florida"),
                new Music("deadmau5", "EDM", "4x4=12", "Bad Selection"),
                new Music("deadmau5", "EDM", "4x4=12", "Animal Rights (with Wolfgang Gartner)"),
                new Music("deadmau5", "EDM", "4x4=12", "I Said (Michael Woods Remix) - (with Chris Lake)"),
                new Music("deadmau5", "EDM", "4x4=12", "Cthulhu Sleeps"),
                new Music("deadmau5", "EDM", "4x4=12", "Right This Second"),
                new Music("deadmau5", "EDM", "4x4=12", "Raise Your Weapon (Edit) - (featuring Greta Svabo Bech)"),
                new Music("deadmau5", "EDM", "4x4=12", "One Trick Pony (featuring SOFI)"),
                new Music("deadmau5", "EDM", "4x4=12", "Everything Before"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Superliminal"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Channel 42 (with Wolfgang Gartner)"),
                new Music("deadmau5", "EDM", "> album title goes here <", "The Veldt (8 Minute Edit) - (featuring Chris James)"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Fn Pig"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Professional Griefers (featuring Gerard Way)"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Maths"),
                new Music("deadmau5", "EDM", "> album title goes here <", "There Might be Coffee"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Take Care of the Proper Paperwork"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Closer"),
                new Music("deadmau5", "EDM", "> album title goes here <", "October"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Sleepless"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Failbait (featuring Cypress Hill)"),
                new Music("deadmau5", "EDM", "> album title goes here <", "Telemiscommunications (with Imogen Heap)"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Avaritia"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Coelacanth I"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Ice Age (deadmau5 Remix) - (by How to Destroy Angels)"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "My Pet Coelacanth"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Infra Turbo Pigcart Racer"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Terrors in My Head"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Creep"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Somewhere Up Here"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Phantoms Can't Hang"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 1", "Gula"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Acedia"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Invidia"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Errors in My Bread"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Survivalism (deadmau5 Remix) - (by Nine Inch Nails)"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Silent Picture"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Rlyehs Lamemnt"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Superbia"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Mercedes"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Bleed"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Ira"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Monday"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "A Moment to Myself"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Pets"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Coelacanth II"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Seeya - (featuring Colleen D'Agostino)"),
                new Music("deadmau5", "EDM", "While(1<2) - Disc 2", "Petting Zoo"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "4ware"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "2448"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Cat Thruster"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Deus Ex Machina"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Glish"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Imaginary Friends"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Let Go - (featuring Grabbitz)"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "No Problem"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Snowcone"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Three Pound Chicken Wing"),
                new Music("deadmau5", "EDM", "W:/2016ALBUM/", "Whelk Then")
        };
    }
}
